sudo: required
services:
  - docker

before_install:
  - docker build -t matheuspaesp/flow -f frontend/Dockerfile.dev frontend/.

script:
  - docker run -e CLI=true matheuspaesp/flow npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-760402862148"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"